apiVersion: apps/v1
kind: Deployment
metadata:
  name: authtm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authtm
  template:
    metadata:
      labels:
        app: authtm
    spec:
      containers:
        - name: authtm
          image: purthas/authtm
          env:
            - name: MONGO_URI
              value: 'mongodb://authtm-mongo-srv:27017/authtm'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: authtm-srv
spec:
  selector:
    app: authtm
  ports:
    - name: authtm
      protocol: TCP
      port: 4000
      targetPort: 4000
