apiVersion: apps/v1
kind: Deployment
metadata:
  name: expirationtm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expirationtm
  template:
    metadata:
      labels:
        app: expirationtm
    spec:
      containers:
        - name: expirationtm
          image: purthas/expirationtm
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expirationtm-redis-srv
