apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: authtm-srv
                port:
                  number: 4000
          - path: /api/tickets/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ticketstm-srv
                port:
                  number: 4001
          - path: /api/orders/?(.*)
            pathType: Prefix
            backend:
              service:
                name: orderstm-srv
                port:
                  number: 4002
          - path: /api/payments/?(.*)
            pathType: Prefix
            backend:
              service:
                name: paymentstm-srv
                port:
                  number: 4003
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: clienttm-srv
                port:
                  number: 3000
