apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderstm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderstm
  template:
    metadata:
      labels:
        app: orderstm
    spec:
      containers:
        - name: orderstm
          image: purthas/orderstm
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://orderstm-mongo-srv:27017/orderstm'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orderstm-srv
spec:
  selector:
    app: orderstm
  ports:
    - name: orderstm
      protocol: TCP
      port: 4002
      targetPort: 4002
