apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketstm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketstm
  template:
    metadata:
      labels:
        app: ticketstm
    spec:
      containers:
        - name: ticketstm
          image: purthas/ticketstm
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://ticketstm-mongo-srv:27017/ticketstm'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketstm-srv
spec:
  selector:
    app: ticketstm
  ports:
    - name: ticketstm
      protocol: TCP
      port: 4001
      targetPort: 4001
